// browser-extension/src/XIT/BURN/DaysCell.tsx
import classNames from 'classnames';
import { settings } from '@src/store/settings';
import { h } from 'preact';
import PrunCss from '@src/prun-ui/prun-css';
import useReactive from '@src/hooks/use-reactive';

export default function DaysCell(props: { days: number }) {
  const days = Math.floor(props.days);
  const { red, yellow } = useReactive(() => ({
    red: settings.burn.red,
    yellow: settings.burn.yellow,
  }));
  const burnClass = classNames({
    [PrunCss.Workforces.daysMissing]: days <= red,
    [PrunCss.Workforces.daysWarning]: days <= yellow,
    [PrunCss.Workforces.daysSupplied]: days > yellow,
  });

  return (
    <td style={{ position: 'relative' }}>
      <div style={{ position: 'absolute', left: 0, top: 0, width: '100%', height: '100%' }} class={burnClass} />
      <span>{days < 500 ? days : '∞'}</span>
    </td>
  );
}

// src/features/XIT/BURN/DaysCell.vue
<script setup lang="ts">
import { userData } from '@src/store/user-data';

const props = defineProps({
  days: {
    type: Number,
    required: true,
  },
});

const days = computed(() => Math.floor(props.days));
const burnClass = computed(() => ({
  [C.Workforces.daysMissing]: days.value <= userData.settings.burn.red,
  [C.Workforces.daysWarning]: days.value <= userData.settings.burn.yellow,
  [C.Workforces.daysSupplied]: days.value > userData.settings.burn.yellow,
}));
</script>

<template>
  <td :style="{ position: 'relative' }">
    <div
      :style="{ position: 'absolute', left: 0, top: 0, width: '100%', height: '100%' }"
      :class="burnClass" />
    <span>{{ days < 500 ? days : '∞' }}</span>
  </td>
</template>
