// browser-extension/src/XIT/BURN/BurnSection.tsx
import useReactive from '@src/hooks/use-reactive';
import { h } from 'preact';
import { CategorySort } from '@src/util';
import { PlanetBurn } from '@src/XIT/BURN/BURN';
import PlanetHeader from '@src/XIT/BURN/PlanetHeader';
import MaterialRow from '@src/XIT/BURN/MaterialRow';

export default function BurnSection(props: { isMultiplanet: boolean; burn: PlanetBurn; dispSettings }) {
  const { isMultiplanet, burn, dispSettings } = props;

  const isMinimized = useReactive(() => dispSettings.minimized && dispSettings.minimized[burn.planetName]);

  const rows = [] as h.JSX.Element[];

  const onHeaderClick = () => {
    if (dispSettings.minimized[burn.planetName]) {
      delete dispSettings.minimized[burn.planetName];
    } else {
      dispSettings.minimized[burn.planetName] = true;
    }

    //setSettings(pmmgSettings);
  };

  if (isMultiplanet) {
    rows.push(<PlanetHeader key={burn.planetName} burn={burn} minimized={isMinimized} onClick={onHeaderClick} />);
  }

  if (!isMinimized) {
    const burnMaterials = Object.keys(burn.burn);
    burnMaterials.sort(CategorySort);

    for (const ticker of burnMaterials) {
      rows.push(
        <MaterialRow
          key={ticker}
          ticker={ticker}
          isMultiplanet={isMultiplanet}
          burn={burn}
          dispSettings={dispSettings}
        />,
      );
    }
  }

  return <tbody>{rows}</tbody>;
}

// browser-extension/src/features/XIT/BURN/BurnSection.vue
<script setup lang="ts">
import { computed, PropType } from 'vue';
import { PlanetBurn } from '@src/core/burn';
import PlanetHeader from '@src/features/XIT/BURN/PlanetHeader.vue';
import MaterialList from '@src/features/XIT/BURN/MaterialList.vue';

const props = defineProps({
  isMultiplanet: Boolean,
  burn: {
    type: Object as PropType<PlanetBurn>,
    required: true,
  },
  dispSettings: {
    type: Object,
    required: true,
  },
});

const dispSettings = computed(() => props.dispSettings);

const isMinimized = computed(
  () => dispSettings.value.minimized && dispSettings.value.minimized[props.burn.planetName],
);

const onHeaderClick = () => {
  if (props.dispSettings.minimized[props.burn.planetName]) {
    delete dispSettings.value.minimized[props.burn.planetName];
  } else {
    dispSettings.value.minimized[props.burn.planetName] = true;
  }
};
</script>

<template>
  <tbody>
    <PlanetHeader :burn="burn" :minimized="isMinimized" :on-click="onHeaderClick" />
  </tbody>
  <tbody :class="{ [$style.collapse]: isMinimized }">
    <MaterialList :is-multiplanet="isMultiplanet" :burn="burn" :disp-settings="dispSettings" />
  </tbody>
</template>

<style module>
.collapse {
  visibility: collapse;
}
</style>
