// src/features/XIT/BURN/MaterialRow.vue
<script setup lang="ts">
import { MaterialBurn } from '@src/core/burn';
import MaterialIcon from '@src/components/MaterialIcon.vue';
import DaysCell from '@src/features/XIT/BURN/DaysCell.vue';
import { fixed0, fixed1, fixed2 } from '@src/utils/format';
import { useTileState } from '@src/features/XIT/BURN/tile-state';
import PrunButton from '@src/components/PrunButton.vue';
import { showBuffer } from '@src/infrastructure/prun-ui/buffers';
import { userData } from '@src/store/user-data';

const props = defineProps({
  material: {
    type: Object as PropType<PrunApi.Material>,
    required: true,
  },
  burn: {
    type: Object as PropType<MaterialBurn>,
    required: true,
  },
});

const production = computed(() => props.burn.DailyAmount);
const invAmount = computed(() => props.burn.Inventory ?? 0);
const isInf = computed(() => production.value >= 0);
const days = computed(() => (isInf.value ? 1000 : props.burn.DaysLeft));

const isRed = computed(() => days.value <= userData.settings.burn.red);
const isYellow = computed(() => days.value <= userData.settings.burn.yellow);
const isGreen = computed(() => days.value > userData.settings.burn.yellow);

const red = useTileState('red');
const yellow = useTileState('yellow');
const green = useTileState('green');
const inf = useTileState('inf');

const isVisible = computed(() => {
  if (isInf.value) {
    return inf.value;
  }
  return (
    (isRed.value && red.value) || (isYellow.value && yellow.value) || (isGreen.value && green.value)
  );
});

const changeText = computed(() => {
  const abs = Math.abs(production.value);
  const fixed = abs >= 1000 ? fixed0(abs) : abs >= 100 ? fixed1(abs) : fixed2(abs);
  return production.value > 0 ? '+' + fixed : production.value < 0 ? '-' + fixed : 0;
});

const changeClass = computed(() => ({
  [C.ColoredValue.positive]: production.value > 0,
}));

const needAmt = computed(() =>
  days.value > userData.settings.burn.resupply || production.value > 0
    ? 0
    : (days.value - userData.settings.burn.resupply) * production.value,
);
</script>

<template>
  <tr v-if="isVisible">
    <td :class="$style.materialContainer">
      <MaterialIcon size="inline-table" :ticker="material.ticker" />
    </td>
    <td>
      <span>{{ fixed0(invAmount) }}</span>
    </td>
    <td>
      <span :class="changeClass">{{ changeText }}</span>
    </td>
    <td>
      <span>{{ isNaN(needAmt) ? '0' : fixed0(needAmt) }}</span>
    </td>
    <DaysCell :days="days" />
    <td>
      <PrunButton dark inline @click="showBuffer(`CXM ${material.ticker}`)">CXM</PrunButton>
    </td>
  </tr>
</template>

<style module>
.materialContainer {
  width: 32px;
  padding: 0;
}
</style>

// browser-extension/src/XIT/BURN/MaterialRow.tsx
import useReactive from '@src/hooks/use-reactive';
import { settings } from '@src/store/settings';
import MaterialIcon from '@src/components/MaterialIcon';
import { h } from 'preact';
import { getMaterialNameByTicker } from '@src/prun-ui/material-names';
import DaysCell from '@src/XIT/BURN/DaysCell';
import { PlanetBurn } from '@src/burn';

export default function MaterialRow(props: {
  material: PrunApi.Material;
  isMultiplanet: boolean;
  burn: PlanetBurn;
  dispSettings;
}) {
  const { material, isMultiplanet, burn, dispSettings } = props;
  const { red, yellow, resupply } = useReactive(() => ({
    red: settings.burn.red,
    yellow: settings.burn.yellow,
    resupply: settings.burn.resupply,
  }));

  const matBurn = burn.burn[material.ticker];
  const days = matBurn.DaysLeft;
  const production = matBurn.DailyAmount;
  const invAmount = matBurn.Inventory ?? 0;

  const isRed = days <= red;
  const isYellow = days <= yellow;
  const isGreen = days > yellow;
  const isInf = production >= 0;

  const isVisible = useReactive(() => {
    if (isInf && !dispSettings.inf) {
      return false;
    }
    return (isRed && dispSettings.red) || (isYellow && dispSettings.yellow) || (isGreen && dispSettings.green);
  });

  if (!isVisible) {
    return null;
  }

  const materialColumnStyle = {
    width: '32px',
    paddingRight: '0px',
    paddingLeft: isMultiplanet ? '32px' : '0px',
  };

  const consText = Math.abs(production) < 1 ? production.toFixed(2) : production.toFixed(1);

  const needAmt = days > resupply || production > 0 ? 0 : (days - resupply) * production;

  return (
    <tr>
      <td style={materialColumnStyle}>
        <MaterialIcon small ticker={material.ticker} />
      </td>
      <td>
        <span style={{ fontWeight: 'bold' }}>{getMaterialNameByTicker(material.ticker)}</span>
      </td>
      <td>
        <span>{consText} / Day</span>
      </td>
      <td>
        <span>{invAmount}</span>
      </td>
      <td>
        <span>{isNaN(needAmt) ? '0' : needAmt.toFixed(0)}</span>
      </td>
      <DaysCell days={days} />
    </tr>
  );
}
