// browser-extension/src/XIT/BURN/SettingsButton.tsx
import classNames from 'classnames';
import PrunCss from '@src/prun-ui/prun-css';
import { h } from 'preact';

export default function SettingsButton(props: { toggled: boolean; text: string; width: number; onClick: () => void }) {
  const { toggled, text, width, onClick } = props;
  const buttonClass = classNames(PrunCss.RadioItem.container, PrunCss.RadioItem.containerHorizontal);
  const barUntoggledClass = classNames(PrunCss.RadioItem.indicator, PrunCss.RadioItem.indicatorHorizontal);
  const barToggledClass = classNames(
    PrunCss.RadioItem.indicator,
    PrunCss.RadioItem.indicatorHorizontal,
    PrunCss.RadioItem.active,
    PrunCss.effects.shadowPrimary,
  );
  const barClass = toggled ? barToggledClass : barUntoggledClass;
  const barStyle = {
    width: `${width}px`,
    maxWidth: `${width}px`,
    height: '2px',
  };
  const textBoxClass = classNames(
    PrunCss.RadioItem.value,
    PrunCss.RadioItem.valueHorizontal,
    PrunCss.fonts.fontRegular,
    PrunCss.type.typeSmall,
  );
  return (
    <span class={buttonClass} onClick={onClick}>
      <div class={barClass} style={barStyle} />
      <div class={textBoxClass}>{text}</div>
    </span>
  );
}

// browser-extension/src/XIT/BURN/SettingsButton.vue
<script setup lang="ts">
import PrunCss from '@src/prun-ui/prun-css';
import { computed, PropType } from 'vue';

const props = defineProps({
  toggled: Boolean,
  text: {
    type: String,
    required: true,
  },
  width: {
    type: Number,
    required: true,
  },
  onClick: {
    type: Function as PropType<() => void>,
    required: true,
  },
});

const buttonClass = [PrunCss.RadioItem.container, PrunCss.RadioItem.containerHorizontal];
const barUntoggledClass = [PrunCss.RadioItem.indicator, PrunCss.RadioItem.indicatorHorizontal];
const barToggledClass = [
  PrunCss.RadioItem.indicator,
  PrunCss.RadioItem.indicatorHorizontal,
  PrunCss.RadioItem.active,
  PrunCss.effects.shadowPrimary,
];
const barClass = computed(() => (props.toggled ? barToggledClass : barUntoggledClass));
const barStyle = computed(() => ({
  width: `${props.width}px`,
  maxWidth: `${props.width}px`,
  height: '2px',
}));
const textBoxClass = [
  PrunCss.RadioItem.value,
  PrunCss.RadioItem.valueHorizontal,
  PrunCss.fonts.fontRegular,
  PrunCss.type.typeSmall,
];
</script>

<template>
  <div :class="buttonClass" @click="onClick">
    <div :class="barClass" :style="barStyle" />
    <div :class="textBoxClass">{{ text }}</div>
  </div>
</template>
