// browser-extension/src/XIT/CONTS/CONTS.tsx
import xit from '../xit-registry';
import { h } from 'preact';
import ContractRow from '@src/XIT/CONTS/ContractRow';
import features from '@src/feature-registry';
import usePrunData from '@src/hooks/use-prun-data';
import { selectContracts, selectContractsFetched } from '@src/prun-api/data/contracts';
import { Loading } from '@src/components/Loading';

function CONTS() {
  const fetched = usePrunData(selectContractsFetched);
  const contracts = usePrunData(selectContracts);

  if (!fetched) {
    return <Loading />;
  }

  const rows = contracts
    .filter(shouldShowContract)
    .sort(compareContracts)
    .map(c => <ContractRow key={c.id} id={c.id} />);

  if (rows.length === 0) {
    rows.push(
      <tr>
        <td colSpan={4}>No active contracts</td>
      </tr>,
    );
  }

  return (
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Material</th>
          <th>Partner&apos;s Conditions</th>
          <th>My Conditions</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
  );
}

function shouldShowContract(contract: PrunApi.Contract) {
  switch (contract.status) {
    case 'OPEN':
    case 'CLOSED':
    case 'PARTIALLY_FULFILLED': {
      return true;
    }
    default: {
      return false;
    }
  }
}

function compareContracts(a: PrunApi.Contract, b: PrunApi.Contract) {
  return (a.date?.timestamp ?? 0) - (b.date?.timestamp ?? 0);
}

function init() {
  xit.add({
    command: ['CONTS', 'CONTRACTS'],
    name: 'ACTIVE CONTRACTS',
    component: () => <CONTS />,
  });
}

features.add({
  id: 'xit-conts',
  init,
});

// browser-extension/src/features/XIT/CONTS/CONTS.vue
<script lang="ts">
import xit from '@src/features/XIT/xit-registry';
import CONTS from '@src/features/XIT/CONTS/CONTS.vue';

xit.add({
  command: ['CONTS', 'CONTRACTS'],
  name: 'ACTIVE CONTRACTS',
  component: () => CONTS,
});

export default {};
</script>

<script setup lang="ts">
import LoadingSpinner from '@src/components/LoadingSpinner.vue';
import { contractsStore } from '@src/infrastructure/prun-api/data/contracts';
import { computed } from 'vue';
import ContractRow from '@src/features/XIT/CONTS/ContractRow.vue';

const filtered = computed(() =>
  contractsStore.all.value.filter(shouldShowContract).sort(compareContracts),
);

function shouldShowContract(contract: PrunApi.Contract) {
  switch (contract.status) {
    case 'OPEN':
    case 'CLOSED':
    case 'PARTIALLY_FULFILLED': {
      return true;
    }
    default: {
      return false;
    }
  }
}

function compareContracts(a: PrunApi.Contract, b: PrunApi.Contract) {
  return (a.date?.timestamp ?? 0) - (b.date?.timestamp ?? 0);
}
</script>

<template>
  <LoadingSpinner v-if="!contractsStore.fetched" />
  <table v-else>
    <thead>
      <tr>
        <th>Contract</th>
        <th>Material</th>
        <th>Partner&apos;s Conditions</th>
        <th>My Conditions</th>
      </tr>
    </thead>
    <tbody>
      <tr v-if="filtered.length === 0">
        <td colspan="4">No active contracts</td>
      </tr>
      <template v-else>
        <ContractRow v-for="contract in filtered" :key="contract.id" :contract="contract" />
      </template>
    </tbody>
  </table>
</template>

<style scoped></style>
