// browser-extension/src/XIT/CONTS/PartnerLink.tsx
import { Link } from '@src/components/Link';
import { h } from 'preact';
import { isFactionContract } from '@src/XIT/CONTS/utils';
import { TextColors } from '@src/Style';

export default function PartnerLink(props: { contract: PrunApi.Contract }) {
  const { contract } = props;
  if (isFactionContract(contract)) {
    return (
      <Link command={`FA ${contract.partner.countryCode}`}>
        <span style={{ color: TextColors.Yellow, fontWeight: 'bold' }} title="Faction Contract">
          ✦&nbsp;
        </span>
        {contract.partner.name}
      </Link>
    );
  }
  if (contract.partner.name) {
    return <Link command={`CO ${contract.partner.code}`}>{contract.partner.name}</Link>;
  }
  if (contract.partner.code) {
    return <Link command={`CO ${contract.partner.code}`} />;
  }
  return <div>{contract.preamble}</div>;
}

// browser-extension/src/features/XIT/CONTS/PartnerLink.vue
<script setup lang="ts">
import { PropType } from 'vue';
import PrunLink from '@src/components/PrunLink.vue';
import { TextColors } from '@src/Style';
import { isFactionContract } from '@src/features/XIT/CONTS/utils';

defineProps({
  contract: {
    type: Object as PropType<PrunApi.Contract>,
    required: true,
  },
});
</script>

<template>
  <PrunLink v-if="isFactionContract(contract)" :command="`FA ${contract.partner.countryCode}`">
    <span :style="{ color: TextColors.Yellow, fontWeight: 'bold' }" title="Faction Contract">
      ✦
    </span>
    {{ contract.partner.name }}
  </PrunLink>
  <PrunLink v-else-if="contract.partner.name" :command="`CO ${contract.partner.code}`">
    {{ contract.partner.name }}
  </PrunLink>
  <PrunLink v-else :command="`CO ${contract.partner.code}`" />
</template>
