// browser-extension/src/XIT/CONTS/PartnerLink.tsx
import { Link } from '@src/components/Link';
import { h } from 'preact';
import { isFactionContract } from '@src/XIT/CONTS/utils';
import { TextColors } from '@src/Style';

export default function PartnerLink(props: { contract: PrunApi.Contract }) {
  const { contract } = props;
  if (isFactionContract(contract)) {
    return (
      <Link command={`FA ${contract.partner.countryCode}`}>
        <span style={{ color: TextColors.Yellow, fontWeight: 'bold' }} title="Faction Contract">
          ✦&nbsp;
        </span>
        {contract.partner.name}
      </Link>
    );
  }
  if (contract.partner.name) {
    return <Link command={`CO ${contract.partner.code}`}>{contract.partner.name}</Link>;
  }
  if (contract.partner.code) {
    return <Link command={`CO ${contract.partner.code}`} />;
  }
  return <div>{contract.preamble}</div>;
}

// src/features/XIT/CONTS/PartnerLink.vue
<script setup lang="ts">
import PrunLink from '@src/components/PrunLink.vue';
import { isFactionContract } from '@src/features/XIT/CONTS/utils';
import fa from '@src/utils/font-awesome.module.css';
import coloredValue from '@src/infrastructure/prun-ui/css/colored-value.module.css';

defineProps<{ contract: PrunApi.Contract }>();
</script>

<template>
  <PrunLink v-if="isFactionContract(contract)" :command="`FA ${contract.partner.countryCode}`">
    <span :class="[fa.regular, coloredValue.warning]">{{ '\uf005' }}</span>
    {{ contract.partner.name }}
  </PrunLink>
  <PrunLink v-else-if="contract.partner.name" :command="`CO ${contract.partner.code}`">
    {{ contract.partner.name }}
  </PrunLink>
  <PrunLink v-else :command="`CO ${contract.partner.code}`" />
</template>
