// browser-extension/src/XIT/CHAT.tsx
import { hourFormatter, dateFormatter } from '../util';
import xit from './xit-registry';
import features from '@src/feature-registry';
import { h } from 'preact';
import { useEffect, useState } from 'preact/compat';
import { Loading } from '@src/components/Loading';

interface ChatMessage {
  MessageTimestamp: number;
  MessageType: 'CHAT' | 'JOINED' | 'LEFT';
  UserName: string;
  MessageText: string;
}

function CHAT(props: { parameters: string[] }) {
  const { parameters } = props;
  const parameter = parameters[1];
  const [isLoaded, setIsLoaded] = useState(false);
  const [data, setData] = useState([] as ChatMessage[]);
  useEffect(() => {
    fetch(`https://rest.fnar.net/chat/display/${parameter}`)
      .then(response => response.json())
      .then(data => {
        setIsLoaded(true);
        setData(data);
      });
  }, [parameter]);

  if (!isLoaded) {
    return <Loading />;
  }

  const lines: h.JSX.Element[] = [];
  for (const messageData of data) {
    const parts: h.JSX.Element[] = [];
    switch (messageData.MessageType) {
      case 'CHAT': {
        parts.push(<div class="chat-name">{messageData.UserName}</div>);
        parts.push(<div class="chat-message">{messageData.MessageText}</div>);
        break;
      }
      case 'JOINED': {
        parts.push(<div class="chat-name" />);
        parts.push(
          <div class="chat-message" style={{ fontStyle: 'italic' }}>
            {messageData.UserName} joined.
          </div>,
        );
        break;
      }
      case 'LEFT': {
        parts.push(<div class="chat-name" />);
        parts.push(
          <div class="chat-message" style={{ fontStyle: 'italic' }}>
            {messageData.UserName} left.
          </div>,
        );
        break;
      }
    }

    lines.push(
      <div class="chat-line">
        <div>
          <div class="time-date">{dateFormatter.format(new Date(messageData.MessageTimestamp))}</div>
          <div class="time-date" style={{ color: '#999999' }}>
            {hourFormatter.format(new Date(messageData.MessageTimestamp))}
          </div>
        </div>
        {parts}
      </div>,
    );
  }

  return (
    <div style={{ height: '100%', flexGrow: 1, paddingTop: '4px' }}>
      <div class="title">{parameter} Global Site Owners</div>
      {lines}
    </div>
  );
}

function init() {
  xit.add({
    command: 'CHAT',
    name: 'FIO CHAT',
    component: parameters => {
      if (parameters.length < 2) {
        return <div>Error! Not Enough Parameters!</div>;
      }

      return <CHAT parameters={parameters} />;
    },
  });
}

features.add({
  id: 'xit-chat',
  init,
});

// browser-extension/src/XIT/CHAT.vue
<script lang="ts">
import xit from '@src/XIT/xit-registry';
import features from '@src/feature-registry';
import CHAT from '@src/XIT/CHAT.vue';

function init() {
  xit.add({
    command: 'CHAT',
    name: 'FIO CHAT',
    vueComponent: CHAT,
  });
}

features.add({
  id: 'xit-chat',
  init,
});

export default {};
</script>

<script setup lang="ts">
import { ref, watchEffect } from 'vue';
import LoadingSpinner from '@src/components/LoadingSpinner.vue';
import { dateFormatter, hourFormatter } from '../util';

interface FioChatMessage {
  MessageTimestamp: number;
  MessageType: 'CHAT' | 'JOINED' | 'LEFT';
  UserName: string;
  MessageText: string;
}

const props = defineProps({
  parameters: {
    type: Array<string>,
    required: true,
  },
});

const isLoaded = ref(false);
const messages = ref([] as FioChatMessage[]);
watchEffect(() => {
  if (props.parameters.length < 2) {
    return;
  }
  const parameter = props.parameters[1];
  fetch(`https://rest.fnar.net/chat/display/${parameter}`)
    .then(response => response.json())
    .then(data => {
      isLoaded.value = true;
      messages.value = data;
    });
});
</script>

<template>
  <div v-if="parameters.length < 2">Error! Not Enough Parameters!</div>
  <LoadingSpinner v-else-if="!isLoaded" />
  <div v-else :style="{ height: '100%', flexGrow: 1, paddingTop: '4px' }">
    <div class="title">{{ parameters[1] }} Global Site Owners</div>
    <div v-for="(message, i) in messages" :key="i" :class="$style.line">
      <div>
        <div :class="$style.date">{{
          dateFormatter.format(new Date(message.MessageTimestamp))
        }}</div>
        <div :class="$style.date" :style="{ color: '#999999' }">
          {{ hourFormatter.format(new Date(message.MessageTimestamp)) }}
        </div>
      </div>
      <template v-if="message.MessageType === 'CHAT'">
        <div :class="$style.name">{{ message.UserName }}</div>
        <div :class="$style.message">{{ message.MessageText }}</div>
      </template>
      <template v-if="message.MessageType === 'JOINED'">
        <div :class="$style.name">{{ message.UserName }}</div>
        <div :class="$style.message" :style="{ fontStyle: 'italic' }">
          {{ message.UserName }} joined.
        </div>
      </template>
      <template v-if="message.MessageType === 'LEFT'">
        <div :class="$style.name" />
        <div :class="$style.message" :style="{ fontStyle: 'italic' }">
          {{ message.UserName }} left.
        </div>
      </template>
    </div>
  </div>
</template>

<style module>
.line {
  width: 100%;
  display: grid;
  grid-template-columns: minmax(8em, 1fr) minmax(8em, 4fr) minmax(8em, 15fr);
  grid-column-gap: 1px;
  font-size: 11px;
  line-height: 1.1;
}

.date {
  color: #444444;
  display: inline-block;
  padding: 2px 5px;
  padding-right: 0px;
  text-align: left;
  white-space: nowrap;
  overflow: hidden;
}

.name {
  display: inline-block;
  text-align: right;
  color: #999999;
  text-overflow: ellipsis;
  padding: 2px 5px;
  border-right: 1px solid #999999;
}

.message {
  display: inline-block;
  text-align: left;
  color: #bbbbbb;
  word-break: break-word;
  padding: 2px 5px;
}
</style>
