// src/features/XIT/CHAT.vue
<script setup lang="ts">
import LoadingSpinner from '@src/components/LoadingSpinner.vue';
import { ddmm, hhmm } from '@src/utils/format';
import { useXitParameters } from '@src/hooks/use-xit-parameters';

interface FioChatMessage {
  MessageTimestamp: number;
  MessageType: 'CHAT' | 'JOINED' | 'LEFT';
  UserName: string;
  MessageText: string;
}

const parameters = useXitParameters();
const parameter = parameters[0];

const isLoaded = ref(false);
const messages = ref([] as FioChatMessage[]);
watchEffect(() => {
  if (!parameter) {
    return;
  }
  fetch(`https://rest.fnar.net/chat/display/${parameter}`)
    .then(response => response.json())
    .then(data => {
      isLoaded.value = true;
      messages.value = data;
    });
});
</script>

<template>
  <div v-if="!parameter">Error! Not Enough Parameters!</div>
  <LoadingSpinner v-else-if="!isLoaded" />
  <div v-else :style="{ height: '100%', flexGrow: 1, paddingTop: '4px' }">
    <div :class="$style.title">{{ parameter }} Global Site Owners</div>
    <div
      v-for="(message, i) in messages"
      :key="i"
      :class="[C.Message.message, C.type.typeRegular, C.fonts.fontRegular]">
      <div :class="C.Message.timestamp">
        <div :class="C.Message.date">{{ ddmm(message.MessageTimestamp) }}</div>
        <div :class="C.Message.time" :style="{ color: '#999999' }">
          {{ hhmm(message.MessageTimestamp) }}
        </div>
      </div>
      <template v-if="message.MessageType === 'CHAT'">
        <div :class="C.Message.name">
          <div :class="[C.Sender.container, C.type.typeRegular, C.fonts.fontRegular]">
            <div :class="[C.Sender.name, $style.name]">
              {{ message.UserName }}
            </div>
          </div>
        </div>
        <div :class="C.Message.controlsAndText">
          <div :class="C.Message.text">
            {{ message.MessageText }}
          </div>
        </div>
      </template>
      <template v-if="message.MessageType === 'JOINED'">
        <div :class="C.Message.name" />
        <div :class="C.Message.controlsAndText">
          <div :class="[C.Message.text, C.Message.system]">{{ message.UserName }} joined.</div>
        </div>
      </template>
      <template v-if="message.MessageType === 'LEFT'">
        <div :class="C.Message.name" />
        <div :class="C.Message.controlsAndText">
          <div :class="[C.Message.text, C.Message.system]">{{ message.UserName }} left.</div>
        </div>
      </template>
    </div>
  </div>
</template>

<style module>
.title {
  font-weight: bold;
  display: block;
  font-size: 16px;
  padding-left: 5px;
}

.name {
  cursor: text;
}
</style>

// browser-extension/src/XIT/CHAT.tsx
import { hourFormatter, dateFormatter } from '../util';
import xit from './xit-registry';
import features from '@src/feature-registry';
import { h } from 'preact';
import { useEffect, useState } from 'preact/compat';
import { Loading } from '@src/components/Loading';

interface ChatMessage {
  MessageTimestamp: number;
  MessageType: 'CHAT' | 'JOINED' | 'LEFT';
  UserName: string;
  MessageText: string;
}

function CHAT(props: { parameters: string[] }) {
  const { parameters } = props;
  const parameter = parameters[1];
  const [isLoaded, setIsLoaded] = useState(false);
  const [data, setData] = useState([] as ChatMessage[]);
  useEffect(() => {
    fetch(`https://rest.fnar.net/chat/display/${parameter}`)
      .then(response => response.json())
      .then(data => {
        setIsLoaded(true);
        setData(data);
      });
  }, [parameter]);

  if (!isLoaded) {
    return <Loading />;
  }

  const lines: h.JSX.Element[] = [];
  for (const messageData of data) {
    const parts: h.JSX.Element[] = [];
    switch (messageData.MessageType) {
      case 'CHAT': {
        parts.push(<div class="chat-name">{messageData.UserName}</div>);
        parts.push(<div class="chat-message">{messageData.MessageText}</div>);
        break;
      }
      case 'JOINED': {
        parts.push(<div class="chat-name" />);
        parts.push(
          <div class="chat-message" style={{ fontStyle: 'italic' }}>
            {messageData.UserName} joined.
          </div>,
        );
        break;
      }
      case 'LEFT': {
        parts.push(<div class="chat-name" />);
        parts.push(
          <div class="chat-message" style={{ fontStyle: 'italic' }}>
            {messageData.UserName} left.
          </div>,
        );
        break;
      }
    }

    lines.push(
      <div class="chat-line">
        <div>
          <div class="time-date">{dateFormatter.format(new Date(messageData.MessageTimestamp))}</div>
          <div class="time-date" style={{ color: '#999999' }}>
            {hourFormatter.format(new Date(messageData.MessageTimestamp))}
          </div>
        </div>
        {parts}
      </div>,
    );
  }

  return (
    <div style={{ height: '100%', flexGrow: 1, paddingTop: '4px' }}>
      <div class="title">{parameter} Global Site Owners</div>
      {lines}
    </div>
  );
}

function init() {
  xit.add({
    command: 'CHAT',
    name: 'FIO CHAT',
    component: parameters => {
      if (parameters.length < 2) {
        return <div>Error! Not Enough Parameters!</div>;
      }

      return <CHAT parameters={parameters} />;
    },
  });
}

features.add({
  id: 'xit-chat',
  init,
});
