// browser-extension/src/XIT/CXTS/CXTS.vue
<script lang="ts">
import xit from '@src/XIT/xit-registry';
import features from '@src/feature-registry';
import CXTS from '@src/XIT/CXTS/CXTS.vue';

function init() {
  xit.add({
    command: ['CXTS'],
    name: 'COMMODITY EXCHANGE TRADES',
    vueComponent: CXTS,
  });
}

features.add({
  id: 'xit-cxts',
  init,
});

export default {};
</script>

<script setup lang="ts">
import { showBuffer } from '@src/util';
import usePrunSelector from '@src/hooks/use-prun-selector';
import { selectCxos } from '@src/prun-api/data/cxos';
import { computed } from 'vue';
import DateRow from '@src/XIT/CXTS/DateRow.vue';
import TradeRow from '@src/XIT/CXTS/TradeRow.vue';
import { sameDay } from '@src/XIT/CXTS/utils';

showBuffer('CXOS', true, true);

const orders = usePrunSelector(selectCxos);

interface OrderTrade {
  order: PrunApi.CXOrder;
  trade: PrunApi.CXTrade;
  date: Date;
}

interface DayTrades {
  date: Date;
  trades: OrderTrade[];
  totals: { [currency: string]: number };
}

const days = computed(() => {
  const trades: OrderTrade[] = [];
  for (const order of orders.value) {
    for (const trade of order.trades) {
      trades.push({
        order,
        trade,
        date: new Date(trade.time.timestamp),
      });
    }
  }
  trades.sort((a, b) => b.date.getTime() - a.date.valueOf());
  const days: DayTrades[] = [];
  if (trades.length === 0) {
    return days;
  }

  let day: DayTrades = {
    date: trades[0].date,
    trades: [],
    totals: {},
  };
  days.push(day);

  for (const trade of trades) {
    const mat = trade.order.material;
    if (!mat) {
      continue;
    }

    if (!sameDay(day.date, trade.date)) {
      day = {
        date: trade.date,
        trades: [],
        totals: {},
      };
      days.push(day);
    }

    day.trades.push(trade);
    const total =
      trade.trade.price.amount * trade.trade.amount * (trade.order.type === 'SELLING' ? 1 : -1);
    const currency = trade.trade.price.currency;
    day.totals[currency] = (day.totals[currency] ?? 0) + total;
  }
  return days;
});
</script>

<template>
  <table>
    <thead>
      <tr>
        <th>Time</th>
        <th>Type</th>
        <th>Ticker</th>
        <th>Partner</th>
        <th>Amount</th>
        <th>Price</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
      <tr v-if="days.length === 0">
        <td colSpan="7">
          <template v-if="orders.length === 0">No (partially) filled orders</template>
          <template v-else>No recent trades</template>
        </td>
      </tr>
      <template v-else>
        <template v-for="group in days" :key="group.date">
          <DateRow :date="group.date" :totals="group.totals" />
          <TradeRow
            v-for="trade in group.trades"
            :key="trade.trade.id"
            :date="trade.date"
            :order="trade.order"
            :trade="trade.trade" />
        </template>
      </template>
    </tbody>
  </table>
</template>

// browser-extension/src/XIT/CXTS.tsx
import xit from './xit-registry';
import { h } from 'preact';
import PrunCss from '@src/prun-ui/prun-css';
import prun from '@src/prun-api/prun';
import { useEffect } from 'preact/compat';
import { showBuffer } from '@src/util';
import useDatabase from '@src/hooks/use-database';
import { selectCxos } from '@src/store/database/selectors';
import features from '@src/feature-registry';

interface Entry {
  order: PrunApi.CXOrder;
  trade: PrunApi.CXTrade;
  timestamp: number;
}

function CXTS() {
  useEffect(() => {
    showBuffer('CXOS 9999', true, true);
  }, []);

  const orders = useDatabase(selectCxos);

  const entries: Entry[] = [];
  for (const order of orders) {
    for (const trade of order.trades) {
      entries.push({
        order,
        trade,
        timestamp: trade.time.timestamp,
      });
    }
  }

  if (entries.length === 0) {
    return <div>No recent trades!</div>;
  }

  entries.sort(({ timestamp: a }, { timestamp: b }) => b - a);

  const rows = [] as h.JSX.Element[];
  let lastDate = new Date(entries[0].timestamp);
  const pendingRows: h.JSX.Element[] = [];
  const accumulatedTotals: { [currency: string]: number } = {};

  for (const { order, trade, timestamp } of entries) {
    const mat = prun.materials.get(order.material.ticker);
    if (!mat) {
      continue;
    }

    const date = new Date(timestamp);
    if (!sameDay(lastDate, date)) {
      const style = {
        borderLeft: 'none',
        borderBottom: '1px solid #2b485a',
        borderTop: '1px solid #2b485a',
      };
      const totals: h.JSX.Element[] = [];
      const keys = Object.keys(accumulatedTotals);
      for (let i = 0; i < keys.length; i++) {
        const key = keys[i];
        const value = accumulatedTotals[key];
        if (value === 0) {
          continue;
        }
        const formatted = formatPrice(value.toFixed(2));
        totals.push(
          <span>
            {formatted} {key}
          </span>,
        );
        if (i !== keys.length - 1) {
          totals.push(<br />);
        }
        accumulatedTotals[key] = 0;
      }
      rows.push(
        <tr key={trade.id}>
          <td colSpan={2} style={style}>
            <span>{formatDate(lastDate)}</span>
          </td>
          {/* This <tr> is needed so both other <tr>s are the same color */}
          <td style={{ display: 'none' }} />
          <td colSpan={5} style={style} class={PrunCss.ComExOrdersTable.number}>
            {totals}
          </td>
        </tr>,
      );
      rows.push(...pendingRows);
      pendingRows.length = 0;
    }

    lastDate = date;
    const total = trade.price.amount * trade.amount * (order.type === 'SELLING' ? 1 : -1);
    const priceLabel = formatPrice(trade.price.amount.toFixed(2));
    const totalLabel = formatPrice(total.toFixed(2));
    const currency = trade.price.currency;
    accumulatedTotals[currency] = (accumulatedTotals[currency] ?? 0) + total;
    const typeClass = order.type === 'SELLING' ? PrunCss.OrderTypeLabel.SELLING : PrunCss.OrderTypeLabel.BUYING;
    const fullTicker = `${mat.ticker}.${order.exchange.code}`;
    const onTimeClick = () => showBuffer(`CXO ${order.id.substring(0, 8)}`);
    const onTickerClick = () => showBuffer(`CXOB ${fullTicker}`);
    pendingRows.push(
      <tr key={trade.id}>
        <td>
          <span class={PrunCss.Link.link} onClick={onTimeClick}>
            {formatTime(date)}
          </span>
        </td>
        <td>
          <span class={typeClass}>{order.type === 'SELLING' ? 'SELL' : 'BUY'}</span>
        </td>
        <td>
          <span class={PrunCss.Link.link} onClick={onTickerClick}>
            {fullTicker}
          </span>
        </td>
        <td>
          <span>{mat.displayName}</span>
        </td>
        <td class={PrunCss.ComExOrdersTable.number}>{trade.amount}</td>
        <td class={PrunCss.ComExOrdersTable.number}>
          {priceLabel} {currency}
        </td>
        <td class={PrunCss.ComExOrdersTable.number}>
          {totalLabel} {currency}
        </td>
      </tr>,
    );
  }

  return (
    <table>
      <thead>
        <tr>
          <th>Time</th>
          <th>Type</th>
          <th>Ticker</th>
          <th>Material</th>
          <th>Amount</th>
          <th>Price</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>{rows}</tbody>
    </table>
  );
}

function sameDay(d1: Date, d2: Date) {
  return d1.getFullYear() === d2.getFullYear() && d1.getMonth() === d2.getMonth() && d1.getDate() === d2.getDate();
}

function formatDate(date: Date) {
  const year = date.getFullYear();
  const month = pad(date.getMonth() + 1);
  const day = pad(date.getDate());

  return `${day}/${month}/${year}`;
}

function formatTime(date: Date) {
  const hours = pad(date.getHours());
  const minutes = pad(date.getMinutes());
  const seconds = pad(date.getSeconds());

  return `${hours}:${minutes}:${seconds}`;
}

function pad(number: number) {
  return (number < 10 ? '0' : '') + number;
}

function formatPrice(x: string) {
  return x.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

function init() {
  xit.add({
    command: ['CXTS'],
    name: 'COMMODITY EXCHANGE TRADES',
    component: () => <CXTS />,
  });
}

features.add({
  id: 'xit-cxts',
  init,
});
